Add OAI UE simulator app in the oai-ue snap

diff --git a/snaps/oai-ue/frontend/run b/snaps/oai-ue/frontend/run
--- a/snaps/oai-ue/frontend/run
+++ b/snaps/oai-ue/frontend/run
@@ -9,6 +9,11 @@ if [ ! -e $UE_EXEC ]; then
     exit 127
 fi
 
+if [ ! -e $UESIM_EXEC ]; then
+    echo "Cannot find $UESIM_EXEC executable"
+    exit 127
+fi
+
 if [ ! -e $USIM_MULTI_EXEC ]; then
     echo "Cannot find $USIM_MULTI_EXEC executable"
     exit 127
@@ -18,7 +23,6 @@ if [ ! -e $USIM_EXEC ]; then
     echo "Cannot find $USIM_EXEC executable"
     exit 127
 fi
-
 
 if [ ! -e $NVRAM_EXEC ]; then
     echo "Cannot find $NVRAM_EXEC executable"
@@ -30,8 +34,16 @@ if [ -r $SNAP_DATA/config_ue.sh ]; then
     . $SNAP_DATA/config_ue.sh
 fi
 
-if [ -r $SNAP_DATA/config_cmd.sh ]; then
-    . $SNAP_DATA/config_cmd.sh
+if [ -r $SNAP_DATA/config_uesim.sh ]; then
+    . $SNAP_DATA/config_uesim.sh
+fi
+
+if [ -r $SNAP_DATA/config_ue_cmd.sh ]; then
+    . $SNAP_DATA/config_ue_cmd.sh
+fi
+
+if [ -r $SNAP_DATA/config_uesim_cmd.sh ]; then
+    . $SNAP_DATA/config_uesim_cmd.sh
 fi
 
 if [ -r $SNAP_DATA/config_usim.sh ]; then
@@ -43,6 +55,11 @@ UE_CONFIG=${UE_CONF_FILE2:-$UE_CONF_FILE}
 
 UE_CMD=${UE_CMD_FILE2:-$UE_CMD_FILE}
 UE_EXEC_ARGS=`cat $UE_CMD`
+
+UESIM_CONFIG=${UESIM_CONF_FILE2:-$UESIM_CONF_FILE}
+UESIM_CMD=${UESIM_CMD_FILE2:-$UESIM_CMD_FILE}
+UESIM_EXEC_ARGS="`cat $UESIM_CMD` -O $UESIM_CONFIG"
+
 
 UE_USIM=${UE_USIM_CONF_FILE2:-$UE_USIM_CONF_FILE}
 UE_USIM_EXEC_ARGS=" -c $UE_USIM -o $CONF_DIR"
@@ -62,52 +79,54 @@ case "$1" in
 	snap info $SNAP_NAME
 	;; 
     "start"  )
-	snap start $SNAP_NAME
+	snap start $SNAP_NAME.$2
 	;;
     "stop" )
-	snap stop $SNAP_NAME
+	snap stop $SNAP_NAME.$2
 	;;
     "restart" )
-	snap restart $SNAP_NAME
+	snap restart $SNAP_NAME.$2
 	;;
     "status" )
-	snap services $SNAP_NAME
+	snap services $SNAP_NAME.$2
 	#systemctl status  snap.$SNAP_NAME.daemon.service
 	;;
     "journal" )
 	journalctl -u snap.$SNAP_NAME.daemon.service
 	;;
     "help" )
-	echo "Usage:          sudo  $SNAP_NAME or $SNAP_NAME.[options] args"
-	echo "Note:           root priviliage required"
+	echo "Usage:                sudo  $SNAP_NAME or $SNAP_NAME.[x] args"
+	echo "                      App [x] is ue or uesim"
+	echo "Note:                 root priviliage required"
 	echo "Options:"
-	echo "  start:        start the $SNAP_NAME daemon"
-	echo "  stop:         stop the $SNAP_NAME daemon"
-	echo "  restart:      restart the $SNAP_NAME daemon"
-	echo "  status:       get the $SNAP_NAME status"
-	echo "  journal:      get the $SNAP_NAME logs"
+	echo "oai-ue.[x]:           run App [x] manually as a process. Run with option -h for available execution options."
+	echo "oai-ue.init:               initialize $SNAP_NAME (after the 1st installation)"
+	echo "oai-ue.[x]-conf-get   get the current $SNAP_NAME.[X] configuration file"
+	echo "oai-ue.[x]-conf-list  list the $SNAP_NAME.[x] configuration files"
+	echo "oai-ue.[x]-conf-set   set the $SNAP_NAME.[x] configuration file"
+	echo "oai-ue.[x]-conf-show  show the path to the $SNAP_NAME.[x] configuration file"
+	echo "oai-ue.ue-cmd-set:    set the $SNAP_NAME configuration file"
+	echo "oai-ue.ue-cmd-get:    get the current $SNAP_NAME configuration file"
+	echo "oai-ue.ue-cmd-show:   show the path to the current $SNAP_NAME configuration file"
+	echo "oai-ue.ue-cmd-list:   list the $SNAP_NAME configuration files"
+	echo "oai-ue.oip:           bring up the $SNAP_NAME UE IP address"
 	echo ""
-	echo "  init:         initialize $SNAP_NAME (after the 1st installation)"
-	echo "  oip:          bring up the $SNAP_NAME UE IP address"
-	echo "  oai-ue:       run $SNAP_NAME manually as a process. Run with option -h for available execution options."
-	echo "  usim-gen:     generate usim data file for single or multi UEs"
-	echo "  usim-print:   print the usim configure data file"
-	echo "  nvram-print:  print the nvram data file"
-	echo "  debug:        debug the $SNAP_NAME with gdb"
-	echo "  conf-set:     set the $SNAP_NAME configuration file"
-	echo "  conf-get:     get the current $SNAP_NAME configuration file"
-	echo "  conf-show:    show the path to the $SNAP_NAME configuration file"
-	echo "  conf-list:    list the $SNAP_NAME configuration files"
-	echo "  cmd-set:      set the $SNAP_NAME configuration file"
-	echo "  cmd-get:      get the current $SNAP_NAME configuration file"
-	echo "  cmd-show:     show the path to the current $SNAP_NAME configuration file"
-	echo "  cmd-list:     list the $SNAP_NAME configuration files"
-	echo "  usim-set:     set the USIM configuration file"
-	echo "  usim-get:     get the current USIM  configuration file"
-	echo "  usim-show:    show the current USIM configuration file"
-	echo "  usim-list:    list the USIM configuration files"
+	echo "oai-ue.[x]-journal    get the $SNAP_NAME.[x] daemon logs"
+	echo "oai-ue.[x]-restart    restart the $SNAP_NAME.[x] daemon"
+	echo "oai-ue.[x]-start      start the $SNAP_NAME.[x] daemon"
+	echo "oai-ue.[x]-status     status the $SNAP_NAME.[x] daemon"
+	echo "oai-ue.[x]-stop       stop the $SNAP_NAME.[x] daemon"
 	echo ""
-	echo "  help:         print this help"
+	echo "oai-ue.usim-gen:      generate usim data file for single or multi UEs"
+	echo "oai-ue.usim-print:    print the usim configure data file"
+	echo "oai-ue.nvram-print:   print the nvram data file"
+	echo "oai-ue.debug:         debug the $SNAP_NAME UE with gdb"
+	echo "oai-ue.usim-set:      set the USIM configuration file"
+	echo "oai-ue.usim-get:      get the current USIM  configuration file"
+	echo "oai-ue.usim-show:     show the current USIM configuration file"
+	echo "oai-ue.usim-list:     list the USIM configuration files"
+	echo ""
+	echo "oai-ue.help:          print this help"
 	;;
 
     "oip" )
@@ -140,7 +159,6 @@ case "$1" in
     "usim-gen")
 	shift 
 	echo "$USIM_MULTI_EXEC $UE_USIM_EXEC_ARGS $@"
-	#export USIM_DIR="$CONF_DIR"
 	$USIM_MULTI_EXEC $UE_USIM_EXEC_ARGS "$@"
 	;;
     "usim-print")
@@ -155,9 +173,33 @@ case "$1" in
 	export NVRAM_DIR="$CONF_DIR"
 	$NVRAM_EXEC -p "$@"
 	;;
-    *)
+    "uesim")
+	shift 
+	echo "$UESIM_EXEC  $UESIM_EXEC_ARGS   $@"
+
+	export USIM_DIR="$CONF_DIR"
+	export NVRAM_DIR="$CONF_DIR"
+	
+	#ln -s $CONF_DIR/.ue_emm.nvram0  .ue_emm.nvram0
+	#ln -s $CONF_DIR/.ue.nvram0      .ue.nvram0
+	#ln -s $CONF_DIR/.usim.nvram0    .usim.nvram0
+
+	$UESIM_EXEC  $UESIM_EXEC_ARGS "$@"
+	;;
+    "ue" )
 	echo "$UE_EXEC  $UE_EXEC_ARGS $@"
 	export LD_LIBRARY_PATH=$SNAP/usr/lib/lapack:$LD_LIBRARY_PATH
+	export USIM_DIR="$CONF_DIR"
+	export NVRAM_DIR="$CONF_DIR"
+	
+	#ln -s $CONF_DIR/.ue_emm.nvram0  .ue_emm.nvram0
+	#ln -s $CONF_DIR/.ue.nvram0      .ue.nvram0
+	#ln -s $CONF_DIR/.usim.nvram0    .usim.nvram0
+	
 	$UE_EXEC  $UE_EXEC_ARGS "$@"
+	;;
+
+    * )
+	echo "unknow run command $1"
 	;;
 esac
