Save for Osama by Robert

diff --git a/juju-charms/xenial/oai-enb/utils/common b/juju-charms/xenial/oai-enb/utils/common
--- a/juju-charms/xenial/oai-enb/utils/common
+++ b/juju-charms/xenial/oai-enb/utils/common
@@ -35,6 +35,8 @@ set_env() {
     enb_conf=/var/snap/oai-ran/current/enb.band7.tm1.50PRB.usrpb210.conf
     cu_conf=/var/snap/oai-ran/current/cu.lte.conf
     du_conf=/var/snap/oai-ran/current/du.lte.band7.10MHz.if4p5.conf
+    rcc_conf=/var/snap/oai-ran/current/rcc.band7.tm1.if4p5.50PRB.conf
+    rru_conf=/var/snap/oai-ran/current/rru.conf
     conf_file=$(oai-ran.enb-conf-get)
 
     # not needed anymore, keeping these for a while
@@ -180,6 +182,9 @@ start_enb_process() {
         if [ "$node_func" = "cu" ]; then
             reset_cu_running_state
         fi
+        if [ "$node_func" = "rcc" ]; then
+            reset_rcc_running_state
+        fi
         #relation-set ${node_func}_running="no"
         exit 1
     else
@@ -187,6 +192,9 @@ start_enb_process() {
         #relation-set ${node_func}_running="yes"
         if [ "$node_func" = "cu" ]; then
             set_cu_running_state
+        fi
+        if [ "$node_func" = "rcc" ]; then
+            set_rcc_running_state
         fi
         juju-log "Running OAI $node_func"
         status-set active "Running"
@@ -202,15 +210,68 @@ set_cu_running_state() {
         done 
     fi
 }
+
 reset_cu_running_state() {
     if [ -n "$(relation-ids cu)" ]; then
-        juju-log "208 found a realtion : The CU is NOT running"
+        juju-log "found a realtion : The CU is NOT running"
         for cu_id in $(relation-ids cu); do
             relation-set -r $cu_id cu_running=no
 			echo "no" >$CHARM_DIR/.cu_running
         done
     fi
 }
+###############################
+set_du_running_state() {
+    DU_UNIT_RUNNING=0
+    # here we are at DU check the CU
+	if [ -n "$(relation-ids du)" ]; then
+		for du_id in $(relation-ids du); do
+			juju-log "Relation id with cu is $du_id"
+			for unit in $(relation-list -r $du_id); do
+				cu_running=$(relation-get -r $du_id cu_running $unit)
+				if [ "$cu_running" == "yes" ]; then
+					CU_UNIT_RUNNING=$((CU_UNIT_RUNNING + 1))
+					echo "yes" >$CHARM_DIR/.cu_running
+				else
+					echo "no" >$CHARM_DIR/.cu_running
+				fi
+			done
+		done
+        if [ $CU_UNIT_RUNNING -gt 0 ]; then
+            juju-log "node_func=$node_func"
+            echo "node_func=$node_func"
+            start_enb_process $node_func
+        else
+            juju-log "common 220 Waiting for F1-CUDU Relation with CU"
+            status-set maintenance "common 220 Add F1-CUDU relation with CU"
+        fi
+	else
+		#juju-log "cu relationd with DU NOT found"
+		juju-log "common 115 Waiting for F1-CUDU Relation with CU"
+		status-set maintenance "common 115 Add F1-CUDU relation with CU"
+	fi
+}
+###################################@
+
+set_rcc_running_state() {
+    RCC_UNIT_RUNNING=0
+    if [ -n "$(relation-ids rcc)" ]; then
+        for rcc_id in $(relation-ids rcc); do
+            relation-set -r $rcc_id rcc_running=yes
+			echo "yes" >$CHARM_DIR/.rcc_running
+        done 
+    fi
+}
+reset_rcc_running_state() {
+    if [ -n "$(relation-ids rcc)" ]; then
+        juju-log "found a realtion : The rcc is NOT running"
+        for rcc_id in $(relation-ids rcc); do
+            relation-set -r $rcc_id rcc_running=no
+			echo "no" >$CHARM_DIR/.rcc_running
+        done
+    fi
+}
+
 
 add_plmn() {
 
@@ -245,7 +306,7 @@ EOF
     sed -r -n "/tr_s_preference /,$ p" $conf_file >>$CHARM_DIR/enb.conf
 
     mv -f $CHARM_DIR/enb.conf $conf_file
-    rm -f $CHARM_DIR/beginning
+    #rm -f $CHARM_DIR/beginning
 
 }
 
@@ -413,9 +474,90 @@ disable_f1() {
     echo "no" >$CHARM_DIR/.cu_running
     echo "no" >$CHARM_DIR/.du_running
 
+    echo "no"  > $CHARM_DIR/.rru_active
+    echo "no"  > $CHARM_DIR/.rcc_active
+    echo "no" >$CHARM_DIR/.rru_running
+    echo "no" >$CHARM_DIR/.rcc_running
+
+    set_env
+}
+###############################################################################
+
+enable_rcc_ecpri() {
+    set_env
+    #enable_cu_f1 $cu_iface_name $cu_ip_addr $DUIP `config-get cu_portc` $DUPORTC `config-get cu_portd` $DUPORTD
+    # TODO to change the config 
+    #sed -r -i "/CU_INTERFACE_NAME_FOR_F1U/ s/\".+\"/\"$1\"/" $conf_file
+    #sed -r -i "/CU_IPV4_ADDRESS_FOR_F1U/ s/\".+\"/\"$2\"/" $conf_file
+
+    # local_if_name_rcc local_address_rcc remote_address_rru local_portc_rrc remote_portc_rru local_portd_rcc remote_portd_rru
+    sed -r -i "/local_if_name/ s/\".+\"/\"$1\"/" $conf_file
+    sed -r -i "/local_address/ s/\".+\"/\"$2\"/" $conf_file
+
+    if [ $# -ge 3 ]; then
+        sed -r -i "/remote_address/ s/\".+\"/\"$3\"/" $conf_file
+        sed -r -i "/local_portc/ s/\".+\"/\"$4\"/" $conf_file
+        sed -r -i "/remote_portc/ s/\".+\"/\"$5\"/" $conf_file
+        sed -r -i "/local_portd/ s/\".+\"/\"$6\"/" $conf_file
+        sed -r -i "/remote_portd/ s/\".+\"/\"$7\"/" $conf_file
+    fi
+    fh_tr_mode=`config-get fh_transport_mode`
+    sed -r -i "s/(tr_preference[ ]*=[ ]*)\".*\"/\1\"$fh_tr_mode\"/" $conf_file
+
+    open-port 22100/tcp
+    oai-ran.enb-conf-set $rcc_conf
     set_env
 }
 
+enable_rru_ecpri() {
+    set_env
+    # TODO to change the config 
+    #sed -r -i "/DU_INTERFACE_NAME_FOR_F1U/ s/\".+\"/\"$1\"/" $conf_file
+    #sed -r -i "/DU_IPV4_ADDRESS_FOR_F1U/ s/\".+\"/\"$2\"/" $conf_file
+
+    # local_if_name_rru local_address_rru remote_address_rcc local_portc_rru remote_portc_rcc local_portd_rru remote_portd_rcc
+    sed -r -i "/local_if_name/ s/\".+\"/\"$1\"/" $conf_file
+    sed -r -i "/local_address/ s/\".+\"/\"$2\"/" $conf_file
+
+    if [ $# -ge 3 ]; then
+        sed -r -i "/remote_address/ s/\".+\"/\"$3\"/" $conf_file
+        sed -r -i "/local_portc/ s/\".+\"/\"$4\"/" $conf_file
+        sed -r -i "/remote_portc/ s/\".+\"/\"$5\"/" $conf_file
+        sed -r -i "/local_portd/ s/\".+\"/\"$6\"/" $conf_file
+        sed -r -i "/remote_portd/ s/\".+\"/\"$7\"/" $conf_file
+    fi
+
+    fh_tr_mode=`config-get fh_transport_mode`
+    sed -r -i "s/(tr_preference[ ]*=[ ]*)\".*\"/\1\"$fh_tr_mode\"/" $conf_file
+
+    open-port 22100/tcp
+    oai-ran.enb-conf-set $rru_conf
+    set_env
+}
+
+disable_ecpri() {
+    # TODO to change the config 
+    #set_env
+    #sed -r -i  "s/(tr_s_preference[ ]*=[ ]*)\"f1\"/\1\"local_mac\"/" $conf_file
+
+    sed -r -i  "s/(tr_n_preference[ ]*=[ ]*)\"f1\"/\1\"local_RRC\"/" $conf_file
+
+    close-port 22100/tcp || true
+    oai-ran.enb-conf-set $enb_conf
+
+    echo "no"  > $CHARM_DIR/.du_active
+    echo "no"  > $CHARM_DIR/.cu_active
+    echo "no" >$CHARM_DIR/.du_running
+    echo "no" >$CHARM_DIR/.cu_running
+
+    echo "no"  > $CHARM_DIR/.rru_active
+    echo "no"  > $CHARM_DIR/.rcc_active
+    echo "no" >$CHARM_DIR/.rru_running
+    echo "no" >$CHARM_DIR/.rcc_running
+
+    set_env
+}
+#################################################################################
 # get from http://www.linuxjournal.com/content/validating-ip-address-bash-script
 validate_ip() {
 
